### ISSUE TITLE
tomli included even if min python version is > 3.11

### ISSUE THREAD

**Issue by sanders41** [sanders41/python-project-generator#403]
The `tomli` package is being included in the `pyproject.toml` and `test_version.py` files even when the minimum Python version is > 3.11. This doesn't make sense because `tomli` is only needed if the python version is <= 3.11.

Generate `pyproject.toml` dependencies when the min python version is 3.12

```toml
[tool.poetry.group.dev.dependencies]
mypy = "1.11.1"
pre-commit = "3.8.0"
pytest = "8.3.2"
pytest-cov = "5.0.0"
ruff = "0.5.6"
tomli = {version = "2.0.1", python = "<3.11"}
```

Generated `test_version.py` when the min python version is 3.12

```py
if sys.version_info < (3, 11):
    import tomli as tomllib
else:
    import tomllib
```
