### ISSUE TITLE
Add Pixi as an option for project manager

### ISSUE THREAD

**Issue by apcamargo** [sanders41/python-project-generator#465]
[Pixi](https://prefix.dev/) offers great convenience for people who rely on the Conda ecosystem, particularly for projects that depend on non-Python packages. Since [Pixi supports `pyproject.toml` files](https://pixi.sh/v0.20.0/advanced/pyproject_toml/), creating a Pixi project becomes as simple as including a `[tool.pixi.project]` section in the `pyproject.toml` file and populating it. The default configuration might look like this:

```toml
[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
```

Users can then add other sections as needed, such as `[tool.pixi.dependencies]` for non-PyPI dependencies.

**Comment by sanders41** [comment]
I'm assuming there would also need to be updates to the dependencies section of the pyproject.toml? I don't use conda, and therefore don't use pixi, so I don't know enough about it to add it myself. If you want to create a PR to add it I'll accept it.

**Comment by apcamargo** [comment]
The dependency section and the dependencies in `pyproject.toml` would remain unchanged, with all dependencies being pulled from PyPI. The only addition would be the `[tool.pixi.project]` section.

On second thought, since Pixi is agnostic to the Python build system the user chooses (`setuptools`, `hatchling`, etc.), it might not be ideal to present it as an alternative to existing options. Instead, it could be a simple Yes/No (by default, No) question that adds the following to `pyproject.toml`:

```toml
[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
```
