### ISSUE TITLE
Extra dev dependencies incorrectly added in some project managers

### ISSUE THREAD

**Issue by sanders41** [sanders41/python-project-generator#533]
At least with uv extra dev dependencies are being added incorrectly. I need to check other managers to see if they also have issues.

```toml
[tool.uv]
dev-dependencies = [
  "mypy==1.11.2",
  "pre-commit==4.0.0",
  "pytest==8.3.3",
  "pytest-asyncio==0.24.0",
  "pytest-cov==5.0.0",
  "ruff==0.6.9",
httpx==0.27.2
types-passlib==1.7.7.20240819
]
```
