### ISSUE TITLE
Update the `pyproject.toml` template to declare version in a dynamic field

### ISSUE THREAD

**Issue by apcamargo** [sanders41/python-project-generator#794]
Some tools, such as `uv`, complain when the `project` section of `pyproject.toml` is missing a required `version` field. To prevent this, the generated `pyproject.toml` could declare version in a dynamic field:

```toml
[project]
name = "{{ project_name }}"
description = "{{ project_description }}"
authors = [
  { name = "{{ creator }}", email = "{{ creator_email }}" },
]
dynamic = ["version"]
```
